# Generated by Django 3.0.6 on 2020-05-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShoppingApp', '0002_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'PRODUCT DETAILS'},
        ),
    ]
