# Generated by Django 3.0.6 on 2020-05-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShoppingApp', '0003_auto_20200522_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_specification',
            field=models.TextField(),
        ),
    ]
