# Generated by Django 3.0.6 on 2020-05-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShoppingApp', '0004_auto_20200522_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_highlights',
            field=models.TextField(),
        ),
    ]
