# Generated by Django 3.0.6 on 2020-05-27 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShoppingApp', '0006_product_product_shortinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodaysDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todaysDeal_offer_Off', models.IntegerField()),
                ('todaysDeal_deal_price', models.IntegerField()),
                ('todaysDeal_product_fk', models.ForeignKey(default='nil', on_delete=django.db.models.deletion.SET_DEFAULT, to='OnlineShoppingApp.Product')),
            ],
        ),
    ]
