# Generated by Django 3.0.6 on 2020-05-29 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShoppingApp', '0007_todaysdeals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todaysdeals',
            options={'verbose_name_plural': "TODAY'S DEALS"},
        ),
        migrations.CreateModel(
            name='NewItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewItems_product_fk', models.ForeignKey(default='nil', on_delete=django.db.models.deletion.SET_DEFAULT, to='OnlineShoppingApp.Product')),
            ],
            options={
                'verbose_name_plural': 'NEW ITEMS',
            },
        ),
    ]
