# Generated by Django 3.0.6 on 2020-06-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShoppingApp', '0009_addtocart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtocart',
            old_name='AddToCart_fk',
            new_name='product',
        ),
    ]
