# Generated by Django 3.0.6 on 2020-06-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShoppingApp', '0011_addtocart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
