# Generated by Django 3.0.6 on 2020-07-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShoppingApp', '0012_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newitems',
            name='NewItems_product_fk',
        ),
        migrations.RemoveField(
            model_name='todaysdeals',
            name='todaysDeal_product_fk',
        ),
        migrations.DeleteModel(
            name='AddToCart',
        ),
        migrations.DeleteModel(
            name='NewItems',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='TodaysDeals',
        ),
    ]
