# Generated by Django 3.0.6 on 2020-07-13 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
        ('Orders', '0002_auto_20200713_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(default='nil', on_delete=django.db.models.deletion.DO_NOTHING, to='Products.Product'),
        ),
    ]
