# Generated by Django 3.0.6 on 2020-07-13 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
        ('Orders', '0005_auto_20200713_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_customer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_deal_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_payment_method',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_shipping_charge',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Products.Product'),
        ),
    ]
