# Generated by Django 3.0.6 on 2020-07-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_auto_20200713_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
