# Generated by Django 3.0.6 on 2020-07-04 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_image', models.FileField(upload_to='documents')),
                ('product_brand', models.CharField(max_length=50)),
                ('product_shortinfo', models.TextField(default='nil')),
                ('product_highlights', models.TextField()),
                ('product_specification', models.TextField()),
                ('product_instock', models.IntegerField()),
                ('product_category', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('product_star_rating', models.IntegerField()),
                ('product_number_of_ratings', models.IntegerField()),
                ('product_offeroff', models.IntegerField()),
                ('product_discount', models.IntegerField()),
                ('product_dealprice', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'PRODUCT DETAILS',
            },
        ),
        migrations.CreateModel(
            name='TodaysDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todaysDeal_offer_Off', models.IntegerField()),
                ('todaysDeal_deal_price', models.IntegerField()),
                ('todaysDeal_product_fk', models.ForeignKey(default='nil', on_delete=django.db.models.deletion.SET_DEFAULT, to='Products.Product')),
            ],
            options={
                'verbose_name_plural': "TODAY'S DEALS",
            },
        ),
        migrations.CreateModel(
            name='NewItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewItems_product_fk', models.ForeignKey(default='nil', on_delete=django.db.models.deletion.SET_DEFAULT, to='Products.Product')),
            ],
            options={
                'verbose_name_plural': 'NEW ITEMS',
            },
        ),
    ]
