# Generated by Django 3.0.6 on 2020-07-21 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerzone_Off', models.IntegerField()),
                ('offerzone_deal_price', models.IntegerField()),
                ('offerzone_product_fk', models.ForeignKey(default='nil', on_delete=django.db.models.deletion.SET_DEFAULT, to='Products.Product')),
            ],
            options={
                'verbose_name_plural': "OFFERS'S ZONE",
            },
        ),
    ]
